library(rmarkdown)
#work_dir <-
args <- commandArgs(trailingOnly = TRUE)
if(length(args)!= 1 | !endsWith(args[1], ".Rmd"))
	stop("Only 1 argument should be passed or not ending with Rmd")
#render("rFilter/segAll.Rmd", "html_document")
#render("rFilter/segComb.Rmd", "html_document")
#render("rFilter/altSeg.Rmd", "html_document")
#render("rFilter/altSeg_old.Rmd", "html_document")
#render("rFilter/visualising_segs.Rmd", "html_document")
#render("altSeg.Rmd", "html_document")
#render("segComb.Rmd", "html_document")
#render("visualising_alternated.Rmd", "html_document")
#render("gene_darmanis.Rmd", "html_document")
render(args[1], "pdf_document")
